### PR TITLE
#553 QoL issues

### LINKED ISSUE #553: QoL issues
Small, quality of life issues identified in Hartshorn

1. The lack of `@Nullable` on the appropriate `Exceptional<T>` parameters means that IntelliSense complains unnecessarily.
2. Support for `TypeContext` in `HartshornUtils#toArray`

### PR DESCRIPTION
**Pull request by pumbas600**
Fixes #553

# Changes

* Added `@Nullable` to appropriate methods in `Exceptional<T>`
* Added a `toArray` method in `HartshornUtils` that takes in a `TypeContext<T>` as a parameter

# Checklist:
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by pumbas600** [comment]
Could we not close this branch / PR so that I can quickly add small QoL fixes where I see them

File: hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java [hunk 1]
```diff
@@ -51,6 +52,7 @@
 
     private static final Exceptional<?> EMPTY = new Exceptional<>();
 
+    @Nullable
```
Comment (GuusLieben) [inline hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java:55]: If the parameter for `throwable` is `@Nullable` at line 484, also make sure the field is marked as nullable, as well as getters for both fields (`#error`, `#type`). Also ensure `#get` is annotated with `@NotNull`

**Review by GuusLieben — CHANGES_REQUESTED** [review]

File: hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java (hunk 1 above)
Comment (pumbas600) [reply hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java:55]: `#error` throws a `NoSuchElementException` if it doesn't exist, so shouldn't it be annotated with `@NotNull` too?

Comment (GuusLieben) [reply hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java]: Indeed you're right, I see you've added it correctly in your last commit, thanks!

**Comment by GuusLieben** [comment]
Always prepend commit messages with the issue number, this way we can trace back where commits came from after they're merged. Please also amend previous commit messages

File: hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java [hunk 2]
```diff
@@ -21,6 +21,8 @@
 import org.dockbox.hartshorn.core.function.CheckedBiFunction;
 import org.dockbox.hartshorn.core.function.CheckedFunction;
 import org.dockbox.hartshorn.core.function.CheckedSupplier;
+import org.jetbrains.annotations.NotNull;
+import org.jetbrains.annotations.Nullable;
```
Comment (GuusLieben) [inline hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java:25]: Quick notice, yesterday I finalized the switch from `org.jetbrains.annotations` to `org.checkerframework`, see 0b8bbf9a8a4ee55259542a25a121c891afac2373, so you'll probably want to update these imports :)

File: hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java [hunk 3]
```diff
@@ -201,7 +209,8 @@ private Exceptional(final Throwable throwable) {
      * @throws NullPointerException
      *         if value is not present and {@code other} is null
      */
-    public T get(final Supplier<? extends T> other) {
+    @NotNull
+    public T get(@NotNull final Supplier<? extends T> other) {
```
Comment (GuusLieben) [inline hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java:213]: To ensure the result of the supplier is also checked as non-null, you could change this to `@NonNull Supplier<@NonNull ? extends T> other`

**Review by GuusLieben — COMMENTED** [review]
Looks good so far, thanks for resolving the minor mentions from my previous review 😃 

Just in case it got lost in the conversation, make sure to switch to Checker Framework so the right annotations are used. The latest version of both `develop` and `release-candidate-4.2.5` can be used for that

File: hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java (hunk 3 above)
Comment (pumbas600) [reply hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java:213]: Didn't even know you could do this, will do!

File: hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java [hunk 4]
```diff
@@ -351,7 +369,8 @@ public boolean caught() {
      * @return The {@link Exceptional}, for chaining
      * @throws NullPointerException If a value is present and {@code defaultValue} is null
      */
-    public Exceptional<T> orElse(final CheckedSupplier<T> defaultValue) {
+    @NonNull
+    public Exceptional<T> orElse(@NonNull final CheckedSupplier<T> defaultValue) {
         if (this.absent()) {
```
Comment (pumbas600) [inline hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java:374]: Hey Diggy, I haven't added `@NonNull` to typed suppliers like these because I felt it might be going a little overboard. I can add them if you want though?

**Comment by pumbas600** [comment]
Also sorry about all the files being added, I did a rebase but Git decided that for some reason I couldn't push unless I merged (even though I was already completely up to date)

File: hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java (hunk 4 above)
Comment (GuusLieben) [reply hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java:374]: Would be nice to have, as long as it's only done to this extent in `Exceptional`

**Comment by GuusLieben** [comment]
> Also sorry about all the files being added, I did a rebase but Git decided that for some reason I couldn't push unless I merged (even though I was already completely up to date)

If you'd like I can clean it later today 🙂

**Comment by pumbas600** [comment]
> If you'd like I can clean it later today 🙂

That would be amazing! (Out of curiosity, how would you go about doing something like that?)
Also for future reference should I force push in situations like these?

**Comment by GuusLieben** [comment]
> Out of curiosity, how would you go about doing something like that?
I checked out your branch and reset it to the last commit before the merge, which was [4ec6667](https://github.com/GuusLieben/Hartshorn/commit/4ec66670f1ea19bf4c83732a4b3b21bacaf70e1d). This allows you to drop the merge commit. As you added a new commit after the merge, [8ddb422](https://github.com/GuusLieben/Hartshorn/commit/8ddb422), all I had to do after resetting was cherry pick that commit so that it would not be lost.  

One thing I always prefer to do is to keep a backup branch of the original, just in case.  

As you correctly rebased before, I didn't have to rebase, though rebasing onto the latest version of `develop` is typically the best way to update your branch. After this the remote history (GitHub) and local history won't match, so force pushing is a must.

> Also for future reference should I force push in situations like these?
Yep! :)
As long as it's a branch you're working on yourself, it's perfectly fine to force push. For example, in #604 I force pushed several times to ensure my branch was up to date, so documentation would also be valid.

**Comment by GuusLieben** [comment]
Do note that your merge seems to have reset your changes to `HartshornUtils`

File: hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java [hunk 5]
```diff
@@ -126,7 +132,8 @@ private Exceptional(final Throwable throwable) {
      *
      * @return The {@link Exceptional}
      */
-    public static <T> Exceptional<T> of(final Callable<T> supplier) {
+    @NonNull
+    public static <T> Exceptional<T> of(@NonNull final Callable<T> supplier) {
```
Comment (GuusLieben) [inline hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java:136]: `Callable<@Nullable T>` would be preferable

File: hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java [hunk 6]
```diff
@@ -240,7 +253,8 @@ public T orNull() {
      * @return The value, if present, otherwise {@code other}
      * @see Exceptional#orNull()
      */
-    public T or(final T other) {
+    @NonNull
+    public T or(@NonNull final T other) {
```
Comment (GuusLieben) [inline hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java:257]: `other` can be nullable, as described in the JavaDoc of this method

File: hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java [hunk 7]
```diff
@@ -251,7 +265,8 @@ public T or(final T other) {
      *
      * @return The throwable, if present, otherwise {@code other}
      */
-    public Throwable or(final Throwable other) {
+    @NonNull
+    public Throwable or(@NonNull final Throwable other) {
```
Comment (GuusLieben) [inline hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java:269]: `other` can be nullable

File: hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java (hunk 4 above)
Comment (GuusLieben) [reply hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java:374]: Do note that most return values are nullable, in this example `T` is nullable

File: hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java [hunk 8]
```diff
@@ -578,17 +607,18 @@ public Throwable unsafeError() {
...
-
+    
     /**
      * Checks if the value is present, and if it is, checks if it is equal to the given value.
      *
      * @param other The value to check for equality
      * @return {@code true} if the value is present and equal to {@code other}, otherwise {@code false}
      */
-    public boolean equal(final Object other) {
+    public boolean equal(@NonNull final Object other) {
```
Comment (GuusLieben) [inline hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java:621]: `other` may be null

**Review by GuusLieben — CHANGES_REQUESTED** [review]
I noticed `#orThrowUnchecked` was not annotated yet, likely this was added in a commit made after you originally started working on this, could you annotate this as well?

File: hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java (hunk 6 above)
Comment (pumbas600) [reply hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java:257]: Wouldn't we have to annotate the return value with `@Nullable` too then?

File: hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java (hunk 8 above)
Comment (pumbas600) [reply hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java:621]: If `other` is nullable, then you would expect it to return true if `value` is null and `other` is null right? However, due to the `this.present()` check, it would instead return false:
image
Would you like me to replace it with `return Objects.equal(this.orNull(), other);`

File: hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java (hunk 6 above)
Comment (pumbas600) [reply hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java:257]: I feel as though it makes more sense to enforce it being `@NonNull` here so that we can keep the result guaranteed to be not null and instead make them use `orNull`

File: hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java (hunk 8 above)
Comment (GuusLieben) [reply hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java:625]: Comparing `null` can yield unexpected behavior, though when it matters it's safe to assume a condition can include `this.present()` manually (so it becomes `typeA.present() && typeA.equal(typeB)`). Your suggestion sounds good 👍🏼

File: hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java (hunk 6 above)
Comment (GuusLieben) [reply hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java]: It may not always be known whether the value passed into `or` will be null or non-null, though I agree with your motivation for it being `NonNull` as it also forces you to think about what could be returned. `NonNull` is fine here 👍🏼

File: hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java [hunk 9]
```diff
@@ -240,7 +257,8 @@ public T orNull() {
      * @return The value, if present, otherwise {@code other}
      * @see Exceptional#orNull()
      */
-    public T or(final T other) {
+    @NonNull
```
Comment (GuusLieben) [inline hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java:260]: If `other` is null the result will also be nullable

**Review by GuusLieben — CHANGES_REQUESTED** [review]

**Review by GuusLieben — APPROVED** [review]

**Comment by GuusLieben** [comment]
As discussed I'll merge this PR with the current changes approved. This way it'll be included correctly in #584
